// src/utils/constants.js
export const USER_ROLES = {
  ADMIN: 'ADMIN',
  LIBRARIAN: 'LIBRARIAN',
  STAFF: 'STAFF',
  BORROWER: 'BORROWER'
};

export const BOOK_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BORROWED: 'BORROWED',
  RESERVED: 'RESERVED',
  UNAVAILABLE: 'UNAVAILABLE'
};

export const BORROW_STATUS = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE'
};

export const FINE_STATUS = {
  OUTSTANDING: 'OUTSTANDING',
  PAID: 'PAID',
  WAIVED: 'WAIVED'
};

export const NOTIFICATION_TYPES = {
  DUE_DATE: 'DUE_DATE',
  OVERDUE: 'OVERDUE',
  RESERVATION: 'RESERVATION',
  NEW_BOOK: 'NEW_BOOK',
  SYSTEM: 'SYSTEM'
};

export const MEMBERSHIP_TYPES = {
  STANDARD: 'STANDARD',
  PREMIUM: 'PREMIUM',
  STUDENT: 'STUDENT',
  SENIOR: 'SENIOR'
};

export const DEFAULT_CONFIG = {
  MAX_BOOKS_PER_BORROWER: 5,
  LOAN_PERIOD_DAYS: 14,
  RENEWAL_PERIOD_DAYS: 7,
  LATE_FEE_PER_DAY: 0.50,
  RESERVATION_HOLD_DAYS: 3
};